environment:
  nodejs_version: "0.10"
  github_auth_token:
    secure: G0cU5afl4gb8zB4hmxW3DHOaXUmYFNRgV9U90Sn48tNvzLu/WprYgC1F1exv1D3j

branches:
  only:
    - master
skip_tags: true

# Create release
install:
  # Get the latest stable version of Node.js or io.js
  - npm config set registry http://registry.npmjs.org/
  - ps: Install-Product node 0
  - npm install
  - cd app && npm version patch && cd ..
  - npm run-script release

# Run tests
test_script:
  - node --version
  - npm --version
  #- npm test # This line is temporarily disabled since the bootstrap tests throw up a GUI.

after_test:
  - ps: $root = Resolve-Path .\release; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName release }

deploy:
  provider: S3
  access_key_id: AKIAIFO3745YZXCHKHAQ
  secret_access_key: 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
  bucket: media-electron
  set_public: true
  folder: squirrel
  artifact: release

# Push back the updated package.json. The version numbers need to keep climbing,
# or the release building process will break.
# Note that this will use a token tied to Tyler's account, but will show Appveyor as the name.
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - git config --global user.email "appveyor@mediacomplete.github.io"
  - git config --global user.name "Appveyor"
  - git checkout master
  - git add app/package.json
  - git commit -m "Appveyor - bumping patch number for successful build"
  - git push

# We want to ignore our own commits.
skip_commits:
  message: /Appveyor - bumping patch number for successful build/


# Don't actually build yet
build: off
